name: 'Get Latest Release Branch'
description: 'Gets the latest release branch'
inputs:
    version:
      description: 'Version [vX.Y.Z]'
      required: false
      default: ''
    release:
      description: 'Release Branch: [release-latest, release-x.y.z, x.y.z]'
      required: false
      default: ''
    repo_owner:
      description: 'Repository Owner'
      required: false
      default: 'windsorcli'
    repo_name:
      description: 'Repository Name'
      required: false
      default: 'cli'
    token:
      description: 'GitHub Token'
      required: true

permissions:
  contents: read

runs:
  using: 'composite'

  steps:      
    - name: Get Latest Release Branch
      id: get_latest_release_branch
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{ inputs.token }}
        script: |
          const owner = '${{ inputs.repo_owner }}';
          const repo = '${{ inputs.repo_name }}';
          const releaseInput = '${{ inputs.release }}';
          const versionInput = '${{ inputs.version }}';
          const validFormat = /^(release-latest|release-[0-9]+\.[0-9]+\.[0-9]+|v?[0-9]+\.[0-9]+\.[0-9]+|[0-9]+\.[0-9]+\.[0-9]+)$/;

          let release = '';
          let version = '';
          let release_number = '';

          if (versionInput !== '') {
            version = versionInput;
          } else {
            if (releaseInput === 'release-latest' || releaseInput === '') {
              const { data: branches } = await github.rest.repos.listBranches({
                owner,
                repo,
              });

              let releaseBranches = branches
                .map(branch => branch.name)
                .filter(name => name.startsWith('release-'))
                .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

              console.log('All branches:', branches.map(branch => branch.name));
              console.log('Filtered release branches:', releaseBranches);

              const validReleaseBranchFormat = /^release-[0-9]+\.[0-9]+\.[0-9]+$/;
              const filteredReleaseBranches = releaseBranches.filter(branch => validReleaseBranchFormat.test(branch));
              releaseBranches = filteredReleaseBranches;

              console.log('Valid release branches:', releaseBranches);

              release = releaseBranches.pop() || 'main';
              console.log('Selected release branch:', release);

            } else {
              release = releaseInput;
              version = '';
            }
          }

          if (release.startsWith('release-')) {
            release_number = release.replace('release-', '');
          } else {
            release_number = release;
          }
          core.exportVariable('version', version);
          core.setOutput('version', version);

          core.exportVariable('release_number', release_number);
          core.setOutput('release_number', release_number);

          core.exportVariable('release', release);
          core.setOutput('release', release);

          console.log(`Version: ${version}`);
          console.log(`Release Number: ${release_number}`);
          console.log(`Release: ${release}`);

