# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  start-codebuild:
    cmds:
      - |
        cd cloudformation; \
        aws codebuild start-build --project-name WindsorBootstrapper --environment-variables-override name=PARAM1,value=value1,name=PARAM2,value=value2

  deploy-cloudformation:
    cmds:
      - |
        cd cloudformation; \
        aws cloudformation deploy \
        --template-file WindsorBootstrapper.yaml \
        --stack-name WindsorBootstrapper \
        --capabilities CAPABILITY_NAMED_IAM

  bootstrap:
    cmds:
      - |
        cd cloudformation; \
        aws codebuild start-build --project-name WindsorBootstrapper

  destroy-cloudformation:
    cmds:
      - |
        cd cloudformation; \
        aws cloudformation delete-stack \
        --stack-name WindsorBootstrapper

  debug-cloudformation:
    cmds:
      - |
        cd cloudformation; \
        aws cloudformation describe-stack-events --stack-name WindsorBootstrapper

  create-bucket:
    cmds:
      - |
        aws s3api create-bucket --bucket windsor-bootstrapper-590183787785 --region us-east-2 --create-bucket-configuration LocationConstraint=us-east-2
        
  upload-source:
    cmds:
      - |
        cd cloudformation/buildspec; \
        zip -r bootstrapper.zip . 
        aws s3 cp bootstrapper.zip s3://windsor-bootstrapper-590183787785/bootstrapper.zip

  default:
    cmds:
      - task --list-all
    silent: true
