# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  BUCKET_NAME: mtv-bootstrapper-test-bucket
  OS: linux
  ARCH: amd64
  WINDSOR_VERSION: 0.5.6
  AQUA_VERSION: 2.49.0-0
  ACTION: up
  REPOSITORY: https://github.com/tvangundy/bootstrapper.git
  BUILD_SPEC: cloudformation/buildspec.yml
  STACK_NAME: WindsorBootstrapper
tasks:

  deploy-cloudformation:
    cmds:
      - |
        cd cloudformation; \
        aws cloudformation deploy \
        --template-file WindsorBootstrapper.yaml \
        --stack-name {{.STACK_NAME}} \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameter-overrides \
          Repository={{.REPOSITORY}} \
          BuildSpec={{.BUILD_SPEC}} \
          BucketName={{.BUCKET_NAME}} \
          StackName={{.STACK_NAME}}

  start-codebuild-up:
    cmds:
      - |
        cd cloudformation; \
        aws codebuild start-build \
          --project-name {{.STACK_NAME}} \
          --environment-variables-override \
            name=BUCKET_NAME,value={{.BUCKET_NAME}} \
            name=OS,value={{.OS}} \
            name=ARCH,value={{.ARCH}} \
            name=WINDSOR_VERSION,value={{.WINDSOR_VERSION}} \
            name=AQUA_VERSION,value={{.AQUA_VERSION}} \
            name=ACTION,value=up

  start-codebuild-down:
    cmds:
      - |
        cd cloudformation; \
        aws codebuild start-build \
          --project-name {{.STACK_NAME}} \
          --environment-variables-override \
            name=BUCKET_NAME,value={{.BUCKET_NAME}} \
            name=OS,value={{.OS}} \
            name=ARCH,value={{.ARCH}} \
            name=WINDSOR_VERSION,value={{.WINDSOR_VERSION}} \
            name=AQUA_VERSION,value={{.AQUA_VERSION}} \
            name=ACTION,value=down

  destroy-cloudformation:
    cmds:
      - |
        cd cloudformation; \
        aws cloudformation delete-stack \
        --stack-name {{.STACK_NAME}}

  debug-cloudformation:
    cmds:
      - |
        cd cloudformation; \
        aws cloudformation describe-stack-events --stack-name {{.STACK_NAME}}

  create-bucket:
    cmds:
      - |
        aws s3api create-bucket --bucket windsor-bootstrapper-590183787785 --region us-east-2 --create-bucket-configuration LocationConstraint=us-east-2
        
  upload-source:
    cmds:
      - |
        cd cloudformation; \
        zip -r bootstrapper.zip . 
        aws s3 cp bootstrapper.zip s3://windsor-bootstrapper-590183787785/bootstrapper.zip

  default:
    cmds:
      - task --list-all
    silent: true
