name: 'Integration Test Harness'
description: 'An action to run the integration test harness'

inputs:
  windsor_up:
    description: 'Run Windsor Up'
    required: false
    default: false
  repo_owner:
    description: 'Repository owner'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
  version:
    description: 'Version'
    required: false        
  release:
    description: 'Release Branch'
    required: false
    default: 'release-latest'
  windsor_test_config:
    description: 'Windsor Test Config'
    required: false
    default: 'ci-self-hosted-tests.yaml'
  token:
    description: 'GitHub Token'
    required: true

permissions:
  contents: read
  
outputs:
  runner_list:
    description: 'List of runners'
  latest_release_branch:
    description: 'Latest release branch'
  version:
    description: 'Version'
  windsor_test_config:
    description: 'Windsor Test Config'

runs:
  using: 'composite'
  steps:
    - name: Debug Workflow - Integration Test Harness
      run: |
        echo "Debugging workflow"
      shell: bash
          
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Confirm inputs.token has a real value
      run: |
        if [ -z "${{ inputs.token }}" ]; then
          echo "inputs.token is empty"
          exit 1
        fi
      shell: bash

    - name: Run Integration Test Prep Action
      uses: ./.github/actions/integration-test-prep
      with:
        repo_owner: ${{ inputs.repo_owner }}
        repo_name: ${{ inputs.repo_name }}
        version: ${{ inputs.version }}
        release: ${{ inputs.release }}
        windsor_test_config: ${{ inputs.windsor_test_config }}
        token: ${{ inputs.token }}    

    - name: Set job outputs
      id: set-job-outputs
      run: |
        runner_list=$(echo '${{ env.runner_list }}' | jq -c .)

        echo "::set-output name=runner_list::$runner_list"
        echo "::set-output name=latest_release_branch::${{ env.latest_release_branch }}"
        echo "::set-output name=version::${{ env.version }}"
        echo "::set-output name=windsor_test_config::${{ env.windsor_test_config }}"

        echo "version=${{ env.version }}"
        echo "release=${{ env.latest_release_branch }}"
        echo "runner_list=${{ env.runner_list }}"
        echo "windsor_test_config=${{ env.windsor_test_config }}"
      shell: bash

    - name: Run Integration Test
      uses: ./.github/actions/integration-test
      with:
        windsor_up: ${{ inputs.windsor_up }}
        version: ${{ steps.set-job-outputs.outputs.version }}
        release: ${{ steps.set-job-outputs.outputs.latest_release_branch }}
        windsor_test_config: ${{ steps.set-job-outputs.outputs.windsor_test_config }}
        token: ${{ inputs.token }}
