version: 0.2

phases:
  install:
    commands:
      - "curl -L -o windsor_0.5.6_linux_amd64.tar.gz https://github.com/windsorcli/cli/releases/download/v0.5.6/windsor_0.5.6_linux_amd64.tar.gz && \
        sudo tar -xzf windsor_0.5.6_linux_amd64.tar.gz -C /usr/local/bin && \
        sudo chmod +x /usr/local/bin/windsor"
      - "export HOME=$(pwd)"
      - "curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.1.1/aqua-installer | bash"
  pre_build:
    commands:
      - "export PATH=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
      - "aqua i"
      - "windsor version"
      # - "sudo service docker start"
      # - "sudo service docker status"
  build:
    commands:
      # - "cd docker"
      # - "docker build -t windsor-systemd ."
      # - "docker run --privileged --rm \
      #   --tmpfs /run \
      #   --tmpfs /run/lock \
      #   -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
      #   windsor-systemd"
      - "export DOCKER_HOST=unix:///var/run/docker.sock"
      - "export WINDSOR_PROJECT_ROOT=$(pwd)"
      - "windsor init local"
      # - "curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq"
      # - "chmod +x /usr/local/bin/yq"
      # - "yq eval '.contexts.local.dns.enabled = true' -i windsor.yaml"
      # - "cat windsor.yaml"
      - "docker images"
      - "docker ps"
      # - "cat /etc/resolv.conf"
      # - "windsor up"
      # - "docker run --rm windsor-systemd windsor version"
