version: 0.2

env:
  variables:
    BUCKET_NAME: mtv-bootstrapper-bucket-2
    OS: linux
    ARCH: amd64
    VERSION: 0.5.6
    AQUA_VERSION: 2.49.0-0
phases:
  install:
    commands:
      - export HOME=$(pwd)
      - export DOCKER_HOST=unix:///var/run/docker.sock
      - export WINDSOR_PROJECT_ROOT=$(pwd)
      - curl -L -o windsor_${VERSION}_${OS}_${ARCH}.tar.gz https://github.com/windsorcli/cli/releases/download/v${VERSION}/windsor_${VERSION}_${OS}_${ARCH}.tar.gz
      - sudo tar -xzf windsor_${VERSION}_${OS}_${ARCH}.tar.gz -C /usr/local/bin
      - sudo chmod +x /usr/local/bin/windsor
      - curl -L -o aqua_${OS}_${ARCH}.tar.gz https://github.com/aquaproj/aqua/releases/download/v${AQUA_VERSION}/aqua_${OS}_${ARCH}.tar.gz
      - mkdir -p aqua
      - tar -xzf aqua_${OS}_${ARCH}.tar.gz -C aqua
      - export PATH=$(pwd)/aqua:$PATH
      - aqua install
      - export PATH=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH
  pre_build:
    commands:
      - windsor version
      - terraform version
      - windsor init aws
  build:
    commands:
      - windsor up
      - aws s3 ls
  post_build:
    commands:
      - windsor down
      - aws s3 rb s3://${BUCKET_NAME} --force
      - aws s3 ls
