name: 'Integration Test Prep'
description: 'Prepares the environment for the integration test'

inputs:
  repo_owner:
    description: 'Repository owner'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
  version:
    description: 'Version'
    required: false
    default: ''
  release_branch:
    description: 'Release Branch'
    required: false
    default: ''
  release_number:
    description: 'Release Number'
    required: false
    default: ''
  windsor_test_config:
    description: 'Windsor Test Config'
    required: false
    default: 'ci-integration-tests.yaml'
  token:
    description: 'GitHub token'
    required: true

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

    - name: Determine Platform Type
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
      with:
        script: |
          const os = require('os');
          const platform = os.platform();
          core.exportVariable('PLATFORM_OS', platform);
          console.log(`Detected platform: ${platform}`);

    - name: Set Windsor Test Config
      uses: actions/github-script@v7
      with:
        script: |
          console.log(`Windsor Test Config: ${{ inputs.windsor_test_config }}`);
          const platform = process.env.PLATFORM_OS;
          const windsorTestConfig = '${{ inputs.windsor_test_config }}';

          console.log(`Platform: ${platform}`);
          console.log(`Incoming: Windsor Test Config: ${{ inputs.windsor_test_config }}`);

          let windsorTestConfigValue;
          if (platform === 'win32') {
            console.log("Setting Windsor Test Config for Windows");
            windsorTestConfigValue = `tests\\configs\\${windsorTestConfig}`;
          } else {
            console.log("Setting Windsor Test Config for Linux/macOS");
            windsorTestConfigValue = `tests/configs/${windsorTestConfig}`;
          }
          console.log(`Outgoing: Windsor Test Config: ${windsorTestConfigValue}`);
          core.exportVariable('windsor_test_config', windsorTestConfigValue);
          console.log(`Windsor Test Config: ${windsorTestConfigValue}`);

    - name: Build Runner List
      uses: ./.github/actions/build-runner-list
      with:
        config_file_path: '${{ env.windsor_test_config }}'

    - name: Print Runner List
      run: |
        echo "Runner List: ${{ env.RUNNER_LIST }}"
        echo "Platform: ${{ env.PLATFORM_OS }}"
      shell: bash
